# NumPy 

1. NumPy is a Python library used for working with arrays.
2. It also has functions for working in domain of linear 
   algebra, fourier transform, and matrices.
3. It was created in 2005 by Travis Oliphant.
4. NumPy aims to provide an array object that is 50x faster 
   than traditional Python Lists.
5. NumPy arrays are stored at one continuous place in memory 
   unlike lists, so processes can access and manipulate them 
   very efficiently.

In [4]:
import numpy as np #importing numpy module as np

arr = np.array([1,2,3,4,5]) #creating an array using numpy
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
#We can check numpy version  by following code
print(np.__version__)

1.24.2


As we already know Numpy is used to work with arrays. The 
array object in Numpy is called ndarray. 

# Dimensions in array

In [6]:
#0-D arrays, or Scalars, are the elements in an array.
arr = np.array(10)
print(arr)

10


In [7]:
#1-D arrays are arrays that has 0-D arrays as its elements .
#It is also called uni-dimensional array. Its the most basic array.
import numpy as np 

arr = np.array([1,2,3,4,5]) 
print(arr)


[1 2 3 4 5]


In [9]:
#2-D array contains 1-D arrays as its elements.
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#3-D arrays contain 2-D arrays as its elements.
import numpy as np
arr = np.array([[[1,2,3,4,],[5,6,7,8,9]]])
print(arr)

Checking dimension of array

In [19]:
import numpy as np

a = np.array(15)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

In [2]:
import numpy as np
arr = np.array([1,2,3,4], ndmin = 5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [8]:
#NumPy array indexing is same as accessing an array element.
import numpy as np

my_array = np.array([1,2,3,4,5])
print(my_array[0])
#we can also iterate through the array using for loop
sum = 0
for i in my_array:
    sum += i 
print(sum)

1
15


In [9]:
import numpy as np
#accessing 2-D and 3-D arrays
my_array2D = np.array([[1,2,3],[4,5,6]])
print(my_array2D[0,1]) #Prints 2 from the first 1-D array.

# we can get access to 3-D array in the same way.
my_array3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(my_array3D[1,0,1]) #Prints out 8 from the second 2D array.

2
8


In [11]:
#Negative Indexing
import numpy as np

my_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(my_array[0,-2]) #prints 4 from the first 1-D array

4


### Slicing arrays

In [18]:
#Slicing in python means taking elemenst from one given index to another given index.
#array[start:end:step] same as we do with traditional python arrays.
import numpy as np

my_array = np.array([1,2,3,4,5,6,7])
print(my_array[2:6]) #will print from 3 to 6
print(my_array[4:]) #will print from element of index to end of array
print(my_array[:4]) #will print from first element till index 3
print(my_array[-3:-1]) #will print from negative 3 index till negative 1 but won't include it.

#Step value is used to determine the step of slicing
print(my_array[1:5:2]) #will print 2 and 4 after skipping indexes 1 and 3
print(my_array[::2]) #will return every other element from the entire array


[3 4 5 6]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


## Slicing 2D arrays

In [6]:
import numpy as np

my_array = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(my_array[0, 1:4 ]) # first argument specifies which 1D arrayd to use then the slicing is as usual.
print(my_array[0:2, 3]) #will return index three from both arrays
print(my_array[0:2 , 2:4]) # will return from index 2-3 (4 !=included) from both arrays


[2 3 4]
[4 8]
[[3 4]
 [7 8]]


# NumPy Data Types

NumPy data types are refered with onw character, Like i for integers, u for unsigned integers, etc.
1. i - Integer
2. b - boolean
3. u - unsigned integer
4. f - float
5. c - complex float
6. m - timedelta
7. M - datetime
8. O - object
7. S - string
8. U - unicode string
9. V - fixed chink of memory for other type (void)


In [8]:
import numpy as np

arr = np.array([1,2,3,4])
arr2 = np.array(['apple', 'banana', 'mango'])
print(arr.dtype)
print(arr2.dtype)

int32
<U6


In [10]:
#Creating Arrays WIth a Defined Data Type
import numpy as np

my_arr = np.array([1,2,3,4], dtype='S')
print(my_arr)
print(my_arr.dtype)

#For i , u , f, S and U we can define size as well.
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32


In [6]:
import numpy as np

arr = np.array([1,0,3,4,5])
print(arr.astype('f')) #We can specify the data type by using astype method with either int.float.str or using single strings like 'f', 'i', etc.
print(arr.astype(float))
print(arr.astype(str))
print(arr.astype(complex))
print(arr.astype(bool))


[1. 0. 3. 4. 5.]
[1. 0. 3. 4. 5.]
['1' '0' '3' '4' '5']
[1.+0.j 0.+0.j 3.+0.j 4.+0.j 5.+0.j]
[ True False  True  True  True]


# Array Copy vs View

1. Copy is a new array whereas , view is an array reference to the original array.
2. Changes in the copy will not reflect in the original array . But changes in the view will reflect in the original array.


In [13]:
import numpy as np
arr = np.array([1,2,3,4,5])

x = arr.copy()
x[1] = 20
print(arr) #There is no change in original array 
print(x) #The new array has the changes

y = arr.view()
y[2] = 30
print(arr) #There is change in original array too!
print(y) 

#We can check if the array owns the data or not.
print(x.base)
print(y.base)

[1 2 3 4 5]
[ 1 20  3  4  5]
[ 1  2 30  4  5]
[ 1  2 30  4  5]
None
[ 1  2 30  4  5]


# Shape of an Array

The shape of an array is the number of elements in each dimension.

In [9]:
#NumPy arrays have an attribute called shape that returns a
#tupe with each index having the number of corresponding elements.
import numpy as np 
arr = np.array([[1,2,3,4] , [5,6,7,8]])
print(arr.shape) 
#returns (2,4) where first 1st dimension has  2 elements and secondhas 4
arr1 = np.array([1,2,3,4])
print(arr1.shape) 
#returns (4,) which shows that first dimension has 4 elements in it and there no other dimension
arr2 = np.array([1,2,3,4] , ndmin= 5)
print(arr2)
print(arr2.shape)
#here the 5th dimension has 1 element that is a 4d array . This continues until we get 4 from the 1D array.

(2, 4)
(4,)
[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


# NumPy Array Reshaping

- Reshaping arrays mean changing the shape of an array.

In [3]:
#Reshaping from 1D to 2D
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9 ,10])
print(arr.reshape(5 , 2)) #the outermost dimension will have 5 arrays , each with 2 elements
#Reshaping from 1D to 3D

my_arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = my_arr.reshape(2 , 2 ,3)
print(newarr)
#the outermost dimension will have 2 elements , with 2 in middle and the innermost will have 3 elements each

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


- The parameters product should be equal to the shape of the array.

In [4]:
print(newarr.base) #It returns original array so it must be a view.

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### Unknown Dimension

In [5]:
newarr = my_arr.reshape(2 , 2, -1)
print(newarr)#returns the same array as above. 
#Passing -1 as the value , and NumPy will calculate this number for us .


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array

In [6]:
import numpy as np

arr = np.array([[1,2,3,4] , [5,6,7,8]])
print(arr.reshape(-1))

[1 2 3 4 5 6 7 8]


# Numpy Array Iteration

In [5]:
import numpy as np

arr = np.array([1,2,3])
for x in arr:
    print(x)

arr2 = np.array([[1,2,3],[4,5,6]])
for x in arr2:
    for y in x:
        print(y)
    print(x)
    

1
2
3
1
2
3
[1 2 3]
4
5
6
[4 5 6]


### Iterating Arrays Using nditer()

In [7]:
import numpy as np
arr = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


### Iterating Array with Different Data Types

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])

for i in np.nditer(arr , flags=['buffered'] , op_dtypes=['S']):
    print(i)



b'1'
b'2'
b'3'
b'4'
b'5'


###  Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of somethings one by one. Sometime we require corrsponding index of the element while iterating, the ndenumerate() method can be used fot those usecases.

In [4]:
import numpy as np

arr = np.array([1,2,3])
for index , x in np.ndenumerate(arr):
    print(index , x)

(0,) 1
(1,) 2
(2,) 3


# NumPy Joining Array

1. concatenation

In [14]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print(np.concatenate((arr1 , arr2) , axis = 0))#the arrays are joined as a column.
print(np.concatenate((arr1 , arr2) , axis  = 1)) # arrays are joined as a row

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


#### Joining Arrays using Stack Functions

In [25]:
import numpy as np 

fruit1 = np.array(['🍇','🍈','🍉','🍊','🍋','🍌'])
fruit2 = np.array(['🍍','🥭','🍎','🍏','🍐','🍑'])
print(np.stack((fruit1 , fruit2) , axis = 0))
print('------------------------')
print(np.stack((fruit1 , fruit2) , axis = 1))
print(np.hstack((fruit1 , fruit2)))#it stacks arrays horizontally
print(np.vstack((fruit1 ,fruit2)))#it stacks arrays vertically
print(np.dstack((fruit1 , fruit2)))#it stacks arrays along the depth

[['🍇' '🍈' '🍉' '🍊' '🍋' '🍌']
 ['🍍' '🥭' '🍎' '🍏' '🍐' '🍑']]
------------------------
[['🍇' '🍍']
 ['🍈' '🥭']
 ['🍉' '🍎']
 ['🍊' '🍏']
 ['🍋' '🍐']
 ['🍌' '🍑']]
['🍇' '🍈' '🍉' '🍊' '🍋' '🍌' '🍍' '🥭' '🍎' '🍏' '🍐' '🍑']
[['🍇' '🍈' '🍉' '🍊' '🍋' '🍌']
 ['🍍' '🥭' '🍎' '🍏' '🍐' '🍑']]
[[['🍇' '🍍']
  ['🍈' '🥭']
  ['🍉' '🍎']
  ['🍊' '🍏']
  ['🍋' '🍐']
  ['🍌' '🍑']]]


### NumPy Splitting Array

In [35]:
import numpy as np

fruit = np.array(['🍇' ,'🍈', '🍉', '🍊', '🍋', '🍌'])
new_fruit = np.array_split(fruit , 2)
print(new_fruit[0])
print(new_fruit[1])

    

['🍇' '🍈' '🍉']
['🍊' '🍋' '🍌']


#### Splitting 2D arrays

In [41]:
import numpy as np
fruit = np.array([['🍇' ,'🍈', '🍉'], ['🍊', '🍋', '🍌']])
new_fruits = np.array_split(fruit , 2)
print(new_fruits) #It returns a 2D array.
print(np.array_split(fruit , 2 , axis = 1))


[array([['🍇', '🍈', '🍉']], dtype='<U1'), array([['🍊', '🍋', '🍌']], dtype='<U1')]
[array([['🍇', '🍈'],
       ['🍊', '🍋']], dtype='<U1'), array([['🍉'],
       ['🍌']], dtype='<U1')]


### NumPy Searching Arrays

In [47]:
import numpy as np

my_array = np.array([1,2,3,2,5,2])
print(np.where(my_array == 2))

#finding values that are odd
print(np.where(my_array%2 == 1))



(array([1, 3, 5], dtype=int64),)
(array([0, 2, 4], dtype=int64),)


#### Search Sorted

The searchsorted() method performs a ninayr search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [2]:
import numpy as np

my_arr = np.array([1,2,3,4,5,6,7,8])
print(np.searchsorted(my_arr ,4 ))
#It will print the index of the specified value where order is maintained.
print(np.searchsorted(my_arr , 4 , side= 'right'))
#By specifing the side the function will return the index where it should be placed,

3
4


In [3]:
#To search for multiple values
import numpy as np

arr = np.array([1,2,3,4,5])
print(np.searchsorted(arr , [1,4,7]))

[0 3 5]


## Numpy Sorting Arrays

In [7]:
num = np.array([6,3,5,1,2,4])
print(np.sort(num))
#We can also sort strings alphabetically
fruits = np.array(['banana' ,'cherry', 'apple'])
print(np.sort(fruits))
#We can also sort boolean arrays.
my_arr = np.array([True , False , True])
print(np.sort(my_arr))
#Sorting 2D arrays
arr2 = np.array([[4,3,6],[5,1,2]])
print(np.sort(arr2))

[1 2 3 4 5 6]
['apple' 'banana' 'cherry']
[False  True  True]
[[3 4 6]
 [1 2 5]]


## NumPy Filter Array

Getting some elements out of an existing aray and creating a new array out of them is called filtering.
- In NumPy , we use boolean index list to filter an array.
- A boolean index list is a list of booleans corresponding to indexes in the array.

In [8]:
arr = np.array([23 ,25,18,22])
x = [True , True , False ,False]
new_arr = arr[x]#It will assign the elements whose index has True in corresponding array
print(new_arr)

#

[23 25]


The common use is to create a filter array based on conditions.

In [11]:
arr = np.array([22 ,21, 46,76,90])

#Creating an empty list which will contain all the boolean values
filter_arr = []

for elements in arr :
    if elements % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[True, False, True, True, True]
[22 46 76 90]


We can do above task in a simple way.

In [12]:
arr = np.array([22 ,21, 46,76,90])

filter_arr = arr % 2 == 0
new_arr = arr[filter_arr]
print(new_arr)

[22 46 76 90]
